import { Download, FileSpreadsheet, Upload } from "lucide-react";
import { useRef, useState } from "react";

export function BulkOperations() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState("");
  const exportCsv = () => { const csv = "sku,name,quantity,selling_price\nNK-AF-43-BLK,حذاء نايكي,24,90000\nIP15-PM-256,آيفون 15 برو,4,1450000"; const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "salix-inventory.csv"; link.click(); URL.revokeObjectURL(url); };
  return <section className="space-y-4 rounded-3xl border border-emerald-100 bg-white p-4 shadow-sm dark:border-emerald-950/50 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="text-[10px] text-slate-400">CSV متوافق مع Excel</span><h2 className="flex items-center gap-2 text-sm font-black"><FileSpreadsheet size={18} className="text-emerald-500" /> استيراد وتصدير جماعي</h2></div><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => inputRef.current?.click()} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-emerald-200 bg-emerald-50/60 text-xs font-black text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><Upload size={20} /> رفع ملف المخزون{fileName && <span className="text-[10px] font-normal">{fileName}</span>}</button><button type="button" onClick={exportCsv} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-black text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><Download size={20} /> تصدير قالب CSV</button></div><input ref={inputRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "")} /><p className="text-[10px] leading-5 text-slate-400">استخدم الأعمدة: SKU، الاسم، الكمية، وسعر البيع. راجع الملف قبل اعتماده لتفادي تغيير جماعي غير مقصود.</p></section>;
}
